run01:
	python3 main.py 1
run02:
	python3 main.py 2
run03:
	python3 main.py 3
run03-1:
	python3 main.py 31
run04:
	python3 main.py 4
run05:
	python3 main.py 5
run06:
	python3 main.py 6
run07:
	python3 main.py 7
