run01:
	python3 main.py 1
run02:
	python3 main.py 2
run03:
	python3 main.py 3
run04:
	python3 main.py 4
run05:
	python3 main.py 5
run06:
	python3 main.py 6
run07:
	python3 main.py 7
run08:
	python3 main.py 8
run09:
	python3 main.py 9
